// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/documents": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "documents"
                ],
                "summary": "Список документов базы знаний",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/out.DocumentListResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/errs.Error"
                        }
                    }
                }
            },
            "post": {
                "description": "Парсит PDF/DOCX/XLSX/изображение через Docling, эмбеддит чанки BGE-M3, пишет в pgvector.",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "documents"
                ],
                "summary": "Загрузка документа в базу знаний",
                "parameters": [
                    {
                        "type": "file",
                        "description": "Файл документа",
                        "name": "file",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Заголовок (по умолчанию — имя файла)",
                        "name": "title",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "default": "report",
                        "description": "book | regulation | scheme | historical_case | report | article | patent (article = GROBID + Semantic Scholar; patent — через обычный Docling-путь, structured-парсинг формулы изобретения не делаем — используйте authors/year для инвентора/даты подачи)",
                        "name": "sourceType",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "default": "flotation",
                        "description": "Домен знаний",
                        "name": "domain",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "default": "ru",
                        "description": "Язык",
                        "name": "language",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "Авторы (через запятую), если известны",
                        "name": "authors",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "Год издания/публикации, если известен",
                        "name": "year",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "Издание/версия, если известно",
                        "name": "edition",
                        "in": "formData"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/out.IngestResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/errs.Error"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/errs.Error"
                        }
                    }
                }
            }
        },
        "/documents/{documentId}": {
            "delete": {
                "tags": [
                    "documents"
                ],
                "summary": "Удаление документа из базы знаний",
                "parameters": [
                    {
                        "type": "string",
                        "description": "UUID документа",
                        "name": "documentId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "Документ удалён"
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/errs.Error"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/errs.Error"
                        }
                    }
                }
            }
        },
        "/health": {
            "get": {
                "description": "Возвращает {\"status\":\"ok\"}, если приложение поднято и обслуживает запросы.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "health"
                ],
                "summary": "Проверка живости сервиса",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/hypotheses/{hypothesisId}/feedback": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "hypotheses"
                ],
                "summary": "Оценка гипотезы экспертом",
                "parameters": [
                    {
                        "type": "string",
                        "description": "UUID гипотезы",
                        "name": "hypothesisId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Вердикт",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/in.SubmitFeedbackRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/out.FeedbackResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/errs.Error"
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "$ref": "#/definitions/errs.Error"
                        }
                    }
                }
            }
        },
        "/runs": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "runs"
                ],
                "summary": "Список прогонов",
                "parameters": [
                    {
                        "type": "integer",
                        "default": 1,
                        "description": "Номер страницы (\u003e=1)",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 20,
                        "description": "Размер страницы (1-100)",
                        "name": "perPage",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/out.RunListResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "Принимает свободный текст (профиль хвостов/проблему), возвращает run сразу в статусе retrieving — дальше поллить GET /runs/{runId}.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "runs"
                ],
                "summary": "Запуск генерации гипотез",
                "parameters": [
                    {
                        "description": "Запрос на генерацию",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/in.CreateRunRequest"
                        }
                    }
                ],
                "responses": {
                    "202": {
                        "description": "Accepted",
                        "schema": {
                            "$ref": "#/definitions/out.RunResponse"
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "$ref": "#/definitions/errs.Error"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/errs.Error"
                        }
                    }
                }
            }
        },
        "/runs/from-excel": {
            "post": {
                "description": "Принимает Хвосты *.xlsx — числа (классы крупности, минеральные формы, Ni/Cu) парсятся детерминированно, без LLM. rawText опционален — дополняет качественные поля (цель, оборудование, ограничения).",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "runs"
                ],
                "summary": "Запуск генерации гипотез из профиля хвостов (Excel)",
                "parameters": [
                    {
                        "type": "file",
                        "description": "Хвосты *.xlsx",
                        "name": "file",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Свободный текст с доп. контекстом (цель, оборудование, ограничения)",
                        "name": "rawText",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "default": "flotation",
                        "description": "База знаний какого домена используется",
                        "name": "domain",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "default": "ru",
                        "description": "Язык гипотез: ru|en|zh",
                        "name": "language",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "JSON domain.RankingWeights — режим экспертной настройки весов",
                        "name": "rankingWeights",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "JSON-массив строк — направления, которые генерация должна обходить",
                        "name": "excludedTopics",
                        "in": "formData"
                    }
                ],
                "responses": {
                    "202": {
                        "description": "Accepted",
                        "schema": {
                            "$ref": "#/definitions/out.RunResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/errs.Error"
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "$ref": "#/definitions/errs.Error"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/errs.Error"
                        }
                    }
                }
            }
        },
        "/runs/{runId}": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "runs"
                ],
                "summary": "Статус и результат прогона",
                "parameters": [
                    {
                        "type": "string",
                        "description": "UUID прогона",
                        "name": "runId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/out.RunResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/errs.Error"
                        }
                    }
                }
            }
        },
        "/runs/{runId}/graph": {
            "get": {
                "description": "Узлы: entity (оборудование/показатель/реагент/...), claim, hypothesis. Рёбра: subject (entity→claim), affects (claim→entity), evidence (claim→hypothesis).",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "runs"
                ],
                "summary": "Граф evidence-связей прогона",
                "parameters": [
                    {
                        "type": "string",
                        "description": "UUID прогона",
                        "name": "runId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/out.GraphResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/errs.Error"
                        }
                    }
                }
            }
        },
        "/runs/{runId}/report.csv": {
            "get": {
                "produces": [
                    "text/csv"
                ],
                "tags": [
                    "runs"
                ],
                "summary": "CSV-отчёт по прогону",
                "parameters": [
                    {
                        "type": "string",
                        "description": "UUID прогона",
                        "name": "runId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "file"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/errs.Error"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/errs.Error"
                        }
                    }
                }
            }
        },
        "/runs/{runId}/report.docx": {
            "get": {
                "produces": [
                    "application/vnd.openxmlformats-officedocument.wordprocessingml.document"
                ],
                "tags": [
                    "runs"
                ],
                "summary": "DOCX-отчёт по прогону",
                "parameters": [
                    {
                        "type": "string",
                        "description": "UUID прогона",
                        "name": "runId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "file"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/errs.Error"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/errs.Error"
                        }
                    }
                }
            }
        },
        "/runs/{runId}/report.jira.json": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "runs"
                ],
                "summary": "Экспорт гипотез как задач в Jira-совместимом JSON",
                "parameters": [
                    {
                        "type": "string",
                        "description": "UUID прогона",
                        "name": "runId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Ключ проекта Jira, напр. HYP",
                        "name": "projectKey",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "default": "Task",
                        "description": "Тип задачи",
                        "name": "issueType",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "file"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/errs.Error"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/errs.Error"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/errs.Error"
                        }
                    }
                }
            }
        },
        "/runs/{runId}/report.md": {
            "get": {
                "produces": [
                    "text/markdown"
                ],
                "tags": [
                    "runs"
                ],
                "summary": "Markdown-отчёт по прогону",
                "parameters": [
                    {
                        "type": "string",
                        "description": "UUID прогона",
                        "name": "runId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/errs.Error"
                        }
                    }
                }
            }
        },
        "/runs/{runId}/report.pdf": {
            "get": {
                "produces": [
                    "application/pdf"
                ],
                "tags": [
                    "runs"
                ],
                "summary": "PDF-отчёт по прогону",
                "parameters": [
                    {
                        "type": "string",
                        "description": "UUID прогона",
                        "name": "runId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "file"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/errs.Error"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/errs.Error"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "domain.KPIEffect": {
            "type": "object",
            "properties": {
                "direction": {
                    "description": "increase | decrease",
                    "type": "string"
                },
                "magnitude": {
                    "type": "string"
                },
                "metric": {
                    "type": "string"
                }
            }
        },
        "domain.RankingWeights": {
            "type": "object",
            "properties": {
                "evidence": {
                    "type": "number"
                },
                "feasibility": {
                    "type": "number"
                },
                "impact": {
                    "type": "number"
                },
                "novelty": {
                    "type": "number"
                },
                "risk": {
                    "type": "number"
                }
            }
        },
        "domain.Scores": {
            "type": "object",
            "properties": {
                "confidence": {
                    "type": "number"
                },
                "evidenceStrength": {
                    "type": "number"
                },
                "feasibility": {
                    "type": "number"
                },
                "impact": {
                    "type": "number"
                },
                "novelty": {
                    "type": "number"
                },
                "riskPenalty": {
                    "type": "number"
                },
                "total": {
                    "type": "number"
                }
            }
        },
        "domain.VerificationStep": {
            "type": "object",
            "properties": {
                "estimatedCost": {
                    "type": "string"
                },
                "estimatedDuration": {
                    "type": "string"
                },
                "resource": {
                    "type": "string"
                },
                "step": {
                    "type": "string"
                },
                "successCriterion": {
                    "type": "string"
                }
            }
        },
        "errs.Error": {
            "type": "object",
            "properties": {
                "caller": {
                    "type": "string"
                },
                "details": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/errs.FieldError"
                    }
                },
                "message": {
                    "type": "string"
                },
                "reason": {
                    "type": "string"
                },
                "type": {
                    "$ref": "#/definitions/errs.Type"
                }
            }
        },
        "errs.FieldError": {
            "type": "object",
            "properties": {
                "field": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                },
                "rule": {
                    "type": "string"
                }
            }
        },
        "errs.Type": {
            "type": "string",
            "enum": [
                "VALIDATION",
                "NOT_FOUND",
                "CONFLICT",
                "TIMEOUT",
                "INTERNAL"
            ],
            "x-enum-comments": {
                "ErrTypeConflict": "409",
                "ErrTypeInternal": "500",
                "ErrTypeNotFound": "404",
                "ErrTypeTimeout": "504",
                "ErrTypeValidation": "422"
            },
            "x-enum-descriptions": [
                "422",
                "404",
                "409",
                "504",
                "500"
            ],
            "x-enum-varnames": [
                "ErrTypeValidation",
                "ErrTypeNotFound",
                "ErrTypeConflict",
                "ErrTypeTimeout",
                "ErrTypeInternal"
            ]
        },
        "in.CreateRunRequest": {
            "type": "object",
            "required": [
                "rawText"
            ],
            "properties": {
                "domain": {
                    "description": "Domain — база знаний какого домена используется (по умолчанию flotation).",
                    "type": "string",
                    "example": "flotation"
                },
                "excludedTopics": {
                    "description": "ExcludedTopics — направления/подходы, которые генерация должна\nобходить (например, уже испробованные и отклонённые ранее).",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "language": {
                    "description": "Language — язык гипотез/обоснований в ответе (по умолчанию ru).",
                    "type": "string",
                    "enum": [
                        "ru",
                        "en",
                        "zh"
                    ],
                    "example": "ru"
                },
                "rankingWeights": {
                    "description": "RankingWeights — режим экспертной настройки: переопределение весов\nкритериев ранжирования (нетронутые поля = дефолт).",
                    "allOf": [
                        {
                            "$ref": "#/definitions/domain.RankingWeights"
                        }
                    ]
                },
                "rawInput": {
                    "type": "object",
                    "additionalProperties": {}
                },
                "rawText": {
                    "type": "string",
                    "example": "Фабрика: КГМК. Породные хвосты 5824591 СМТ..."
                }
            }
        },
        "in.SubmitFeedbackRequest": {
            "type": "object",
            "required": [
                "verdict"
            ],
            "properties": {
                "comment": {
                    "type": "string",
                    "maxLength": 2000
                },
                "reviewer": {
                    "type": "string",
                    "maxLength": 200
                },
                "verdict": {
                    "type": "string",
                    "enum": [
                        "confirmed",
                        "rejected",
                        "needs_revision"
                    ],
                    "example": "confirmed"
                }
            }
        },
        "out.DocumentListResponse": {
            "type": "object",
            "properties": {
                "items": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/out.DocumentResponse"
                    }
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "out.DocumentResponse": {
            "type": "object",
            "properties": {
                "chunkCount": {
                    "type": "integer"
                },
                "createdAt": {
                    "type": "string"
                },
                "domain": {
                    "type": "string",
                    "example": "flotation"
                },
                "id": {
                    "type": "string"
                },
                "language": {
                    "type": "string",
                    "example": "ru"
                },
                "sourceType": {
                    "type": "string",
                    "example": "book"
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "out.FeedbackResponse": {
            "type": "object",
            "properties": {
                "comment": {
                    "type": "string"
                },
                "createdAt": {
                    "type": "string"
                },
                "hypothesisId": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "reviewer": {
                    "type": "string"
                },
                "verdict": {
                    "type": "string"
                }
            }
        },
        "out.GraphEdgeResponse": {
            "type": "object",
            "properties": {
                "from": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "label": {
                    "type": "string"
                },
                "to": {
                    "type": "string"
                },
                "type": {
                    "description": "subject | affects | evidence",
                    "type": "string",
                    "example": "evidence"
                }
            }
        },
        "out.GraphNodeResponse": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                },
                "kind": {
                    "type": "string"
                },
                "label": {
                    "type": "string"
                },
                "type": {
                    "description": "entity | claim | hypothesis",
                    "type": "string",
                    "example": "entity"
                }
            }
        },
        "out.GraphResponse": {
            "type": "object",
            "properties": {
                "edges": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/out.GraphEdgeResponse"
                    }
                },
                "nodes": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/out.GraphNodeResponse"
                    }
                }
            }
        },
        "out.HypothesisResponse": {
            "type": "object",
            "properties": {
                "createdAt": {
                    "type": "string"
                },
                "criticNotes": {
                    "type": "string"
                },
                "evidenceRefs": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "expectedKpiEffect": {
                    "$ref": "#/definitions/domain.KPIEffect"
                },
                "id": {
                    "type": "string"
                },
                "mechanism": {
                    "type": "string"
                },
                "noveltyReason": {
                    "type": "string"
                },
                "rank": {
                    "type": "integer"
                },
                "risks": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "runId": {
                    "type": "string"
                },
                "scores": {
                    "$ref": "#/definitions/domain.Scores"
                },
                "statement": {
                    "type": "string"
                },
                "verificationPlan": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/domain.VerificationStep"
                    }
                }
            }
        },
        "out.IngestResponse": {
            "type": "object",
            "properties": {
                "chunksIngested": {
                    "type": "integer"
                }
            }
        },
        "out.ProblemSpecResponse": {
            "type": "object",
            "properties": {
                "availableEquipment": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "constraints": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "horizon": {
                    "type": "string"
                },
                "lossHotspots": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "plant": {
                    "type": "string"
                },
                "targetKpi": {
                    "type": "string"
                },
                "targetMetals": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "out.RunListResponse": {
            "type": "object",
            "properties": {
                "items": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/out.RunResponse"
                    }
                },
                "page": {
                    "type": "integer"
                },
                "perPage": {
                    "type": "integer"
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "out.RunResponse": {
            "type": "object",
            "properties": {
                "completedAt": {
                    "type": "string"
                },
                "createdAt": {
                    "type": "string"
                },
                "domain": {
                    "type": "string"
                },
                "error": {
                    "type": "string"
                },
                "hypotheses": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/out.HypothesisResponse"
                    }
                },
                "id": {
                    "type": "string"
                },
                "knowledgeGaps": {
                    "description": "KnowledgeGaps — металлы/точки потерь из ProblemSpec, слабо покрытые\nизвлечёнными claims (детерминированная проверка, не LLM-догадка).",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "language": {
                    "type": "string"
                },
                "problemSpec": {
                    "$ref": "#/definitions/out.ProblemSpecResponse"
                },
                "status": {
                    "type": "string",
                    "example": "retrieving"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/v1",
	Schemes:          []string{},
	Title:            "Фабрика гипотез — Hypothesis Factory API",
	Description:      "Evidence-Backed Hypothesis Factory: генерация проверяемых технологических гипотез по обогащению руд на основе базы знаний (RAG).",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
